Add tag action and reducer
amandahogan/eda-job-list pull request #19
Opened 2017-03-02 08:08 UTC by amandahogan

2017-03-02 08:26 UTC, Quinn-H commented on src/actions/tags.js
> +      value: value
when object property name  and value have same name, you can simplify it by only write property name. like this 
`payload: {
         id: nextTagId++,
         categoryId,
         value
}`

2017-03-02 08:35 UTC, davidchristie requested changes
The `companies` reducer needs to be modified as well so that whenever a tag is added it gets added to the `tags` property of the specified company.

2017-03-02 08:35 UTC, davidchristie commented on src/actions/tags.js
> +      value: value
Please change to:
`   categoryId,
    value
`

2017-03-02 08:35 UTC, davidchristie commented on src/reducers/tags.js
> +]
Looks good! Please change the initial state `companies` to match these tags.
I.e. Company id=0 will start with a `tags` array equal to `[0]`

2017-03-02 23:50 UTC, Quinn-H approved these changes

2017-03-03 00:19 UTC, davidchristie approved these changes

2017-03-03 00:19 UTC, merged